name       : yaml
version    : 0.2.1
release    : 3
source     :
    - https://pyyaml.org/download/libyaml/yaml-0.2.1.tar.gz : 78281145641a080fb32d6e7a87b9c0664d611dcb4d542e90baf731f51cbb59cd
license    : MIT
component  : system.utils
summary    : LibYAML
description: |
    LibYAML is a YAML parser and emitter library.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
