name       : yaml
version    : 0.2.5
release    : 6
source     :
    - https://github.com/yaml/libyaml/archive/refs/tags/0.2.5.tar.gz : fa240dbf262be053f3898006d502d514936c818e422afdcf33921c63bed9bf2e
license    : MIT
component  : system.utils
summary    : LibYAML
description: |
    LibYAML is a YAML parser and emitter library.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
