name       : yaml
version    : 0.2.2
release    : 5
source     :
    - https://github.com/yaml/libyaml/archive/0.2.2.tar.gz : 46bca77dc8be954686cff21888d6ce10ca4016b360ae1f56962e6882a17aa1fe
license    : MIT
component  : system.utils
summary    : LibYAML
description: |
    LibYAML is a YAML parser and emitter library.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
