name       : yaml
version    : 0.1.7
release    : 2
source     :
    - http://pyyaml.org/download/libyaml/yaml-0.1.7.tar.gz : 8088e457264a98ba451a90b8661fcb4f9d6f478f7265d48322a196cec2480729
license    : MIT
component  : system.utils
summary    : LibYAML
description: |
    LibYAML is a YAML 1.1 parser and emitter written in C.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
