name       : yaml
version    : 0.2.1
release    : 4
source     :
    - https://github.com/yaml/libyaml/archive/0.2.1.tar.gz : 1d2aeb87f7d317f1496e4c39410d913840714874a354970300f375eec9303dc4
license    : MIT
component  : system.utils
summary    : LibYAML
description: |
    LibYAML is a YAML parser and emitter library.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
