name       : yaml
version    : 0.1.5
release    : 1
source     :
    - http://pyyaml.org/download/libyaml/yaml-0.1.5.tar.gz : fa87ee8fb7b936ec04457bc044cd561155e1000a4d25029867752e543c2d3bef
license    : MIT
summary    : LibYAML
description: |
    LibYAML is a YAML 1.1 parser and emitter written in C.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
